version: '3.9'

networks:
  net1:

services:
  db:
    image: postgres:13.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: admin
      POSTGRES_DB: asyncio_hw
    networks:
      net1:
        aliases:
          - database

